### ISSUE TITLE
Error on melpa-check deps

### ISSUE THREAD

**Issue by ericdallo** [akirak/emacs-package-checker#7]
I'm using NixOS 20.03 and for some reason, cachix is not working when running `melpa-check deps`:

 ```bash
$ melpa-check deps

MustBeRoot "Run command as root OR execute: $ echo \"trusted-users = root $USER\" | sudo tee -a /etc/nix/nix.conf && sudo pkill nix-daemon"child_process.js:650
    throw err;
    ^

Error: Command failed: cachix use emacs-ci
    at checkExecSyncError (child_process.js:629:11)
    at Object.execFileSync (child_process.js:647:13)
    at /nix/store/iw84dymap8hdlcdkylx7sqwklxc5z776-dist.js:4505:51
    at __do (/nix/store/iw84dymap8hdlcdkylx7sqwklxc5z776-dist.js:7331:17)
    at /nix/store/iw84dymap8hdlcdkylx7sqwklxc5z776-dist.js:1933:22
    at __do (/nix/store/iw84dymap8hdlcdkylx7sqwklxc5z776-dist.js:7626:189)
    at Object.main (/nix/store/iw84dymap8hdlcdkylx7sqwklxc5z776-dist.js:1933:22)
    at Object.<anonymous> (/nix/store/iw84dymap8hdlcdkylx7sqwklxc5z776-dist.js:14775:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```
Then I ran as root:

```bash
$ sudo melpa-check deps

Cachix configuration written to /etc/nixos/cachix.nix.
Binary cache emacs-ci configuration written to /etc/nixos/cachix/emacs-ci.nix.

To start using cachix add the following to your /etc/nixos/configuration.nix:

    imports = [ ./cachix.nix ];

Then run:

    $ sudo nixos-rebuild switch
==================================================
Version information
==================================================
nix-env (Nix) 2.3.4
cachix 0.3.7

--------------------------------------------------
/root/.config/nix/nix.conf
--------------------------------------------------
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/root/.config/nix/nix.conf'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at /nix/store/iw84dymap8hdlcdkylx7sqwklxc5z776-dist.js:5585:25
    at __do (/nix/store/iw84dymap8hdlcdkylx7sqwklxc5z776-dist.js:7088:86)
    at __do (/nix/store/iw84dymap8hdlcdkylx7sqwklxc5z776-dist.js:7633:100)
    at Object.main (/nix/store/iw84dymap8hdlcdkylx7sqwklxc5z776-dist.js:1933:22)
    at Object.<anonymous> (/nix/store/iw84dymap8hdlcdkylx7sqwklxc5z776-dist.js:14775:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```
I followed the instructions and added the import to my nix configuration, but keeps the same output as above.

**Comment by ericdallo** [comment]
Maybe related: https://github.com/cachix/cachix/issues/262

**Comment by akirak** [comment]
Thanks, I didn't notice this issue.

I'm using NixOS, but I personally add myself to `wheel` group and `@wheel` user to `nix.trustedUsers`. It doesn't fail on GitHub Actions, but it runs as the root user. I'll find out a workaround.

**Comment by akirak** [comment]
I've fixed the "no such file or directory" error, but I am not sure if running the command as root is the right way to use cachix. For now, you can manually set up cachix for `nix-emacs-ci` instead of running `melpa-check deps`. That's what the command is doing now. On CI, you can use the GitHub action.

I won't close this issue until I find a proper solution to the problem.

**Comment by akirak** [comment]
I have rewritten this project (even though it's still in alpha), so I will close this issue.

**Comment by ericdallo** [comment]
@akirak you should take a look on Github official [super-linter](https://github.com/github/super-linter) , I have [an issue there](https://github.com/github/super-linter/issues/144) too.

**Comment by akirak** [comment]
@ericdallo I didn't know of the project, and it looks highly important. Thank you for the pointer.

**Comment by ericdallo** [comment]
It's pretty recent, and it seems to be bash only, I tried to setup a elisp linter on that issue, I but could not setup the docker image for emacs :/
Feel free to take a look and work on my branch if you want

**Comment by akirak** [comment]
Maybe I'll ~~create another~~ work on the PR later. I first have to check if it works for existing projects.
